FROM ubuntu:18.04
EXPOSE 80
RUN apt-get update
RUN apt-get -y install apache2
RUN apt-get -y install python3.8

RUN a2enmod cgi

ADD ./conf/apache2_with_python_cgi.conf /etc/apache2/apache2.conf

RUN echo "ServerName localhost" >> /etc/apache2/conf-available/servername.conf
RUN a2enconf servername
RUN service apache2 restart

ADD ./scripts/backup_check_response.py /var/www/html/backup_check_response.py

RUN chmod -R u+rwx,g+x,o+x /var/www/html
RUN ln -sf /usr/bin/python3.8 /usr/local/python3.8

CMD /usr/sbin/apache2ctl -D FOREGROUND
