version: '3'

services:
  db:
    image: mysql:8.0
    container_name: db
    volumes:
      - /volume1/Backup/SE06/SQL/LATEST/mitsm_business_warehouse.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bwng
    ports:
      - "33307:3306"

  python:
    image: python:3.8-alpine
    container_name: python
    volumes:
      - /volume1/backup_check/scripts/compare_uids.py:/tmp/compare_uids.py
      - /volume1/backup_check/data:/data
    tty: true
